# Generated by Django 5.2.1 on 2025-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
