# Generated by Django 5.2.1 on 2025-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_produit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='numero',
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
