# Generated by Django 5.2.1 on 2025-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_facture_numero_alter_facture_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
